# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='addresses',
            fields=[
                ('street', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_placed', models.DateField()),
                ('time_placed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('parent_category', models.CharField(max_length=30)),
                ('number_of_items_sold', models.IntegerField()),
                ('number_of_items_contained', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='credit_cards',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
                ('security_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='emails',
            fields=[
                ('address', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='item_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('verified_purchase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_date', models.DateField()),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=30)),
                ('order_time', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ship_date', models.DateField()),
                ('confirmed_purchase', models.BooleanField(default=False)),
                ('shipment_status', models.CharField(choices=[('SHIP', 'item_shipped'), ('PROCESS', 'item_order_processing'), ('CANCEL', 'item_order_canceled')], max_length=10)),
                ('tracking_number', models.IntegerField()),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.credit_cards')),
            ],
        ),
        migrations.CreateModel(
            name='part_of_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='database.categories')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_inst', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registered_user_id', models.AutoField(default='0', primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('addresses', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.addresses')),
                ('credit_cards', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.credit_cards')),
                ('emails', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.emails')),
            ],
        ),
        migrations.CreateModel(
            name='sale_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=100)),
                ('place_of_origin', models.CharField(max_length=50)),
                ('amount_in_stock', models.IntegerField()),
                ('initial_sale_date', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('auction_end_date', models.DateField(null=True)),
                ('auction_end_time', models.DateTimeField(null=True)),
                ('valid_auction', models.IntegerField(default=0, null=True)),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sells',
            fields=[
                ('type', models.CharField(choices=[('A', 'auction_items'), ('L', 'listed_price_items')], max_length=10)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('average_rating', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('sells', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.sells')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.sale_items')),
                ('user_rater', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='database.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_purchases', models.IntegerField()),
                ('list_name', models.CharField(max_length=30)),
                ('item', models.ManyToManyField(to='database.sale_items')),
            ],
        ),
        migrations.CreateModel(
            name='user_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('verified_purchase', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.sale_items')),
                ('ratee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratees', to='database.RegisteredUser')),
                ('rater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raters', to='database.RegisteredUser')),
            ],
        ),
        migrations.AddField(
            model_name='sale_items',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.sells'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='list',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.user_list'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='sells',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.sells'),
        ),
        migrations.AddField(
            model_name='part_of_category',
            name='item',
            field=models.ManyToManyField(to='database.sale_items'),
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sale_items'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ship_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.addresses'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='item_rating',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.sale_items'),
        ),
        migrations.AddField(
            model_name='item_rating',
            name='user_rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='bids',
            name='item_bid_on',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.sale_items'),
        ),
    ]
