# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='registered_user_id',
        ),
    ]
