# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_registereduser_registered_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_inst', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
